FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# collectAPI

collectAPI is a simple API that have a purpose of facilitate the communication between 
station and company that buys recycle dump.

## Register [/api/v1/register]
### Register [POST] 

+ Request (application/json)

        {
            "name": "yourName",
            "address": "yourAddress",
            "telephone": "+5587541265"
            "email": "example@example.com",
            "password": "thePassword",
            "role": "company"
        }


+ Response 200 (application/json)

        {
            "success"=> true,
            "message"=> "Thanks for signing up!"
        }


## Login [/api/v1/login]
### Login [POST] 

+ Request (application/json)

        {
            "email": "example@example.com",
            "password": "thePassword"
        }


+ Response 200 (application/json)

        {
            "success": true,
            "data": {
                "token": "______"
            }
        }

## Logout [/api/v1/user/logout]
### Logout [POST] 

+ Request (application/json)
    
    + Headers
        Location: /api/v1/user/logout?token=token

+ Response 200 (application/json)

        {
            "success" => true, 
            "message"=> "You have successfully logged out."
        }
        
+ Response 500 (application/json)

        {
            "success" => false, 
            "message"=> "Failed to logout, please try again."
        }