FORMAT: 1A
HOST: http://domain/api/v1

# collectAPI

collectAPI is a simple API that have a purpose of facilitate the communication between
station and company that buys recycle dump.

# Group Auth
## User-Register [/register]
### Register [POST]
+ Request (application/json)

    + Attributes

        + name: `yourName` (required)
        + address: `yourAddress` (required)
        + telephone: `+5587541265` (required)
        + email: `email@example.com` (required)
        + password: `password` (required)
        + role: `company` (required) - It can be station too

+ Response 200 (application/json)

        {
            "message"=> "Thanks for signing up!"
        }

+ Response 400 (application/json)

        {
            "message"=>
            {
                "name":["error_message"],
                "email":["error_message"],
                "address":["error_message"],
                "telephone":["error_message"]
            }
        }


## User-Login [/login]
### Login [POST]
+ Request (application/json)
    
    + Attributes

        + email: `email@example.com` (required)
        + password: `password` (required)


+ Response 200 (application/json)

        {
            "data": {
                "token": {
                    "headers": [],
                    "original": {
                        "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xOTIuMTY4Ljk5LjEwMDo4MDgwXC9hcGlcL3YxXC9sb2dpbiIsImlhdCI6MTUzMzg1NDM4OCwiZXhwIjoxNTMzODU3OTg4LCJuYmYiOjE1MzM4NTQzODgsImp0aSI6ImJmZmZPQXVtbXJ0eDJWQkIiLCJzdWIiOjQsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.ROLeSWU8kyG2qDbDwy-ye9IVWtLO6bnf-DLf2nkou1Y",
                        "token_type": "bearer",
                        "expires_in": 3600
                    },
                    "exception": null
                },
                "user": {
                    "name": "Germano Barcelos",
                    "email": "email@gmail.com",
                    "address": "Rua Iretama, 476, Novo Eldorado, Contagem",
                    "telephone": "(31)996307181"
                }
            }
        }

+ Response 404 (application/json)

        {
            "message": "Email or password is wrong"
        }

## User [/user]
### Profile [GET /profile]
+ Request (application/json)
        
    + Headers
    
                Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xOTIuMTY4Ljk5LjEwMDo4MDgwXC9hcGlcL3YxXC9sb2dpbiIsImlhdCI6MTUzMjg4MzAxMCwiZXhwIjoxNTMyODg2NjEwLCJuYmYiOjE1MzI4ODMwMTAsImp0aSI6ImhOQ0wxTzBXa2s4VXJSOVIiLCJzdWIiOjQsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.3SUKcJbM4a9SWZQAT0r5agNUZKXT424EaRyM8fKQHXI

+ Response 200 (application/json)

        {
            "name": "Germano Barcelos",
            "email": "email@gmail.com",
            "address": "Rua Iretama, 476, Novo Eldorado, Contagem",
            "telephone": "(31)996307181"
        }


### Station [GET /station/{station_id}]

+ Parameters
    
    + station_id: 5 (number, required)
    
+ Request (application/json)
        
    + Headers
    
                Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xOTIuMTY4Ljk5LjEwMDo4MDgwXC9hcGlcL3YxXC9sb2dpbiIsImlhdCI6MTUzMjg4MzAxMCwiZXhwIjoxNTMyODg2NjEwLCJuYmYiOjE1MzI4ODMwMTAsImp0aSI6ImhOQ0wxTzBXa2s4VXJSOVIiLCJzdWIiOjQsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.3SUKcJbM4a9SWZQAT0r5agNUZKXT424EaRyM8fKQHXI

+ Response 200 (application/json)

        {
            "name": "Facebook",
            "email": "email@gmail.com",
            "address": "a",
            "telephone": "852741963"
        }

### Company [GET /company/{company_id}]

+ Parameters
    
    + company_id: 5 (number, required)
    
+ Request (application/json)
        
    + Headers
    
                Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xOTIuMTY4Ljk5LjEwMDo4MDgwXC9hcGlcL3YxXC9sb2dpbiIsImlhdCI6MTUzMjg4MzAxMCwiZXhwIjoxNTMyODg2NjEwLCJuYmYiOjE1MzI4ODMwMTAsImp0aSI6ImhOQ0wxTzBXa2s4VXJSOVIiLCJzdWIiOjQsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.3SUKcJbM4a9SWZQAT0r5agNUZKXT424EaRyM8fKQHXI

+ Response 200 (application/json)

        {
            "name": "AirBNB",
            "email": "email@gmial.com",
            "address": "a",
            "telephone": "852741963"
        }

### Logout [POST /logout]
+ Request (application/json)
        
    + Headers
    
                Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xOTIuMTY4Ljk5LjEwMDo4MDgwXC9hcGlcL3YxXC9sb2dpbiIsImlhdCI6MTUzMjg4MzAxMCwiZXhwIjoxNTMyODg2NjEwLCJuYmYiOjE1MzI4ODMwMTAsImp0aSI6ImhOQ0wxTzBXa2s4VXJSOVIiLCJzdWIiOjQsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.3SUKcJbM4a9SWZQAT0r5agNUZKXT424EaRyM8fKQHXI

+ Response 200 (application/json)

        {
            "message"=> "You have successfully logged out."
        }

+ Response 500 (application/json)

        {
            "message"=> "Failed to logout, please try again."
        }
             
# Group Types
## Type Collection [/types]
### Create Types [POST]
+ Request (application/json)
    
    + Headers
                
                Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xOTIuMTY4Ljk5LjEwMDo4MDgwXC9hcGlcL3YxXC9sb2dpbiIsImlhdCI6MTUzMjg4MzAxMCwiZXhwIjoxNTMyODg2NjEwLCJuYmYiOjE1MzI4ODMwMTAsImp0aSI6ImhOQ0wxTzBXa2s4VXJSOVIiLCJzdWIiOjQsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.3SUKcJbM4a9SWZQAT0r5agNUZKXT424EaRyM8fKQHXI

+ Response 200 (application/json)
    + Attributes

        + type: `type` (required)

+ Response 200 (application/json)

        {
            "data": {
                "id": 1,
                "type": "plastic"
            }
        }

### List Types [GET]
+ Request (application/json)
    
    + Headers
                
                Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xOTIuMTY4Ljk5LjEwMDo4MDgwXC9hcGlcL3YxXC9sb2dpbiIsImlhdCI6MTUzMjg4MzAxMCwiZXhwIjoxNTMyODg2NjEwLCJuYmYiOjE1MzI4ODMwMTAsImp0aSI6ImhOQ0wxTzBXa2s4VXJSOVIiLCJzdWIiOjQsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.3SUKcJbM4a9SWZQAT0r5agNUZKXT424EaRyM8fKQHXI

+ Response 200 (application/json)

        {
            "data": [
                {
                    "id": 1,
                    "type": "plastic"
                }
            ],
            "meta": {
                "pagination": {
                    "total": 1,
                    "count": 1,
                    "per_page": 12,
                    "current_page": 1,
                    "total_pages": 1,
                    "links": []
                }
            }
        }

## Type [/types/{type_id}]
### Show [GET]

+ Parameters
    + type_id: 1 (number, required)

+ Request (application/json)
    
    + Headers
                
                Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xOTIuMTY4Ljk5LjEwMDo4MDgwXC9hcGlcL3YxXC9sb2dpbiIsImlhdCI6MTUzMjg4MzAxMCwiZXhwIjoxNTMyODg2NjEwLCJuYmYiOjE1MzI4ODMwMTAsImp0aSI6ImhOQ0wxTzBXa2s4VXJSOVIiLCJzdWIiOjQsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.3SUKcJbM4a9SWZQAT0r5agNUZKXT424EaRyM8fKQHXI

+ Response 200 (application/json)

        {
            "data": {
                "id": 1,
                "type": "plastic"
            }
        }

+ Response 404 (application/json)

        {
            "error": {
                "message": "Could not found type",
                "status_code": 404
            }
        }

### Update Types [POST]
+ Parameters
    + type_id: 1 (number, required)
+ Request (application/json)
    
    + Headers
                
                Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xOTIuMTY4Ljk5LjEwMDo4MDgwXC9hcGlcL3YxXC9sb2dpbiIsImlhdCI6MTUzMjg4MzAxMCwiZXhwIjoxNTMyODg2NjEwLCJuYmYiOjE1MzI4ODMwMTAsImp0aSI6ImhOQ0wxTzBXa2s4VXJSOVIiLCJzdWIiOjQsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.3SUKcJbM4a9SWZQAT0r5agNUZKXT424EaRyM8fKQHXI

   + Attributes

        + type: type(required)

+ Response 200 (application/json)

        {
            "data": {
                "id": 1,
                "type": "type"
            }
        }

+ Response 404 (application/json)

        {
            "error": {
                "message": "Could not found type",
                "status_code": 404
            }
        }

### Delete Type [DELETE]
+ Parameters
    + type_id: 1 (number, required)

+ Request (application/json)
    
    + Headers
                
                Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xOTIuMTY4Ljk5LjEwMDo4MDgwXC9hcGlcL3YxXC9sb2dpbiIsImlhdCI6MTUzMjg4MzAxMCwiZXhwIjoxNTMyODg2NjEwLCJuYmYiOjE1MzI4ODMwMTAsImp0aSI6ImhOQ0wxTzBXa2s4VXJSOVIiLCJzdWIiOjQsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.3SUKcJbM4a9SWZQAT0r5agNUZKXT424EaRyM8fKQHXI

+ Response 200 (application/json)

+ Response 404 (application/json)

        {
            "error": {
                "message": "Could not found type",
                "status_code": 404
            }
        }

# Group Station Sell
## CStationSell Collection [/stationSells]
### Create Station Sell [POST]
+ Request (application/json)
        
    + Headers
                
                Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xOTIuMTY4Ljk5LjEwMDo4MDgwXC9hcGlcL3YxXC9sb2dpbiIsImlhdCI6MTUzMjg4MzAxMCwiZXhwIjoxNTMyODg2NjEwLCJuYmYiOjE1MzI4ODMwMTAsImp0aSI6ImhOQ0wxTzBXa2s4VXJSOVIiLCJzdWIiOjQsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.3SUKcJbM4a9SWZQAT0r5agNUZKXT424EaRyM8fKQHXI

    + Attributes

        + price      : `150.0`    (number, required)
        + quantity   : `40`       (number, required)
        + type_id    : `1`        (number, required)
        + station_id : `5`        (number, required)

+ Response 200 (application/json)

          {
            "data": {
            "id": 1,
            "price": "150.00",
            "quantity": "40.0",
              "type": {
                  "link": "/api/v1/types/1"
              },
              "station": {
                  "link": "/api/v1/user/station/5"
              }
            }
          }

### List Station Sell [GET /stationSells{?orderByPrice,priceLessThan,priceMoreThan,quantityLessThan,quantityMoreThan,stationName,type,limit}]

+ Parameters
    + orderByPrice: asc (string, optional) - It can be "asc" or "desc"
    + priceLessThan: 150 (number, optional)
    + priceMoreThan: 100 (number, optional)
    + quantityLessThan: 30 (number, optional)
    + quantityMoreThan: 50 (number, optional)
    + stationName: face (string, optional) - It search for string like you write not exactly you write
    + type: plastic (string, optional) - It search for string like you write not exactly you write
    + limit: 2 (number, optional)

+ Request (applcation/json)
    
    + Headers
                
                Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xOTIuMTY4Ljk5LjEwMDo4MDgwXC9hcGlcL3YxXC9sb2dpbiIsImlhdCI6MTUzMjg4MzAxMCwiZXhwIjoxNTMyODg2NjEwLCJuYmYiOjE1MzI4ODMwMTAsImp0aSI6ImhOQ0wxTzBXa2s4VXJSOVIiLCJzdWIiOjQsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.3SUKcJbM4a9SWZQAT0r5agNUZKXT424EaRyM8fKQHXI


+ Response 200 (application/json)

          {
            "data": [
              {
                  "id": 4,
                  "price": "300.00",
                  "quantity": "100.0",
                  "type": {
                      "link": "/api/v1/types/1"
                  },
                  "station": {
                      "link": "/api/v1/user/station/5"
                  }
              },
              {
                  "id": 3,
                  "price": "200.00",
                  "quantity": "60.0",
                  "type": {
                      "link": "/api/v1/types/1"
                  },
                  "station": {
                      "link": "/api/v1/user/station/5"
                  }
              }
            ],
            "meta": {
              "pagination": {
                  "total": 8,
                  "count": 2,
                  "per_page": 2,
                  "current_page": 1,
                  "total_pages": 4,
                  "links": {
                      "next": "http://domain/api/v1/stationSells?page=2"
                  }
              }
            }
          }

## Single Station Sell [/stationSells/{stationSell_id}]
### Show Station Sell [GET]

+ Parameters
    + stationSell_id: 4 (number, required)

+ Request (application/json)
    
    + Headers
                
                Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xOTIuMTY4Ljk5LjEwMDo4MDgwXC9hcGlcL3YxXC9sb2dpbiIsImlhdCI6MTUzMjg4MzAxMCwiZXhwIjoxNTMyODg2NjEwLCJuYmYiOjE1MzI4ODMwMTAsImp0aSI6ImhOQ0wxTzBXa2s4VXJSOVIiLCJzdWIiOjQsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.3SUKcJbM4a9SWZQAT0r5agNUZKXT424EaRyM8fKQHXI

+ Response 200 (application/json)

          {
            "data": {
              "id": 4,
              "price": "300.00",
              "quantity": "100.0",
              "type": {
                  "link": "/api/v1/types/1"
              },
              "station": {
                  "link": "/api/v1/user/station/5"
              }
            }
          }

+ Response 404 (application/json)

          {
            "error": {
              "message": "Could not found sell of station",
              "status_code": 404
            }
          }

### Update Station Sell [POST]
+ Parameters
    + stationSell_id: 4 (number, required)

+ Request (application/json)
    
    + Headers
                
                Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xOTIuMTY4Ljk5LjEwMDo4MDgwXC9hcGlcL3YxXC9sb2dpbiIsImlhdCI6MTUzMjg4MzAxMCwiZXhwIjoxNTMyODg2NjEwLCJuYmYiOjE1MzI4ODMwMTAsImp0aSI6ImhOQ0wxTzBXa2s4VXJSOVIiLCJzdWIiOjQsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.3SUKcJbM4a9SWZQAT0r5agNUZKXT424EaRyM8fKQHXI

    + Attributes

        + price      : `150.0`    (number, required)
        + quantity   : `90`      (number, required)
        + type_id    : `1`        (number, required)
        + station_id : `5`        (number, required)

+ Response 200 (application/json)

          {
            "data": {
              "id": 4,
              "price": "150",
              "quantity": "90",
              "type": {
                  "link": "/api/v1/types/1"
              },
              "station": {
                  "link": "/api/v1/user/station/5"
              }
            }
          }

+ Response 404 (application/json)

          {
            "error": {
              "message": "Could not found sell of station",
              "status_code": 404
            }
          }

### Delete Station Sell [DELETE]
+ Parameters
    + stationSell_id: 4 (number, required)

+ Request (application/json)
    
    + Headers
                
                Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xOTIuMTY4Ljk5LjEwMDo4MDgwXC9hcGlcL3YxXC9sb2dpbiIsImlhdCI6MTUzMjg4MzAxMCwiZXhwIjoxNTMyODg2NjEwLCJuYmYiOjE1MzI4ODMwMTAsImp0aSI6ImhOQ0wxTzBXa2s4VXJSOVIiLCJzdWIiOjQsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.3SUKcJbM4a9SWZQAT0r5agNUZKXT424EaRyM8fKQHXI


+ Response 200 (application/json)

+ Response 404 (application/json)

        {
            "error": {
              "message": "Could not found sell of station",
              "status_code": 404
            }
          }

# Group Company Buy
## Company Buy Collection [/companyBuys]
### Create Company Buy [POST]
+ Request (application/json)
    
    + Headers
                
                Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xOTIuMTY4Ljk5LjEwMDo4MDgwXC9hcGlcL3YxXC9sb2dpbiIsImlhdCI6MTUzMjg4MzAxMCwiZXhwIjoxNTMyODg2NjEwLCJuYmYiOjE1MzI4ODMwMTAsImp0aSI6ImhOQ0wxTzBXa2s4VXJSOVIiLCJzdWIiOjQsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.3SUKcJbM4a9SWZQAT0r5agNUZKXT424EaRyM8fKQHXI


    + Attributes

        + company_id     : `4`      (number, required)
        + stationSell_id : `4`        (number, required)

+ Response 200 (application/json)

          {
            "data": {
              "id": 5,
              "stationSell": {
                "link": "/api/v1/stationSells/4"
              },
              "company": {
                "link": "/api/v1/user/companies/4"
              }
            }
          }

### List Company Buy [GET /companyBuys{?orderByPrice,priceLessThan,priceMoreThan,stationName,type,limit}]

+ Parameters
    + orderByPrice: `asc` (string, optional)
    + priceLessThan: `150` (number, optional)
    + priceMoreThan: `100` (number, optional)
    + stationName: `face` (string, optional)
    + type: `plastic` (string, optional)
    + limit: `3` (number, optional)
    
+ Request (applcation/json)
    
    + Headers
                
                Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xOTIuMTY4Ljk5LjEwMDo4MDgwXC9hcGlcL3YxXC9sb2dpbiIsImlhdCI6MTUzMjg4MzAxMCwiZXhwIjoxNTMyODg2NjEwLCJuYmYiOjE1MzI4ODMwMTAsImp0aSI6ImhOQ0wxTzBXa2s4VXJSOVIiLCJzdWIiOjQsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.3SUKcJbM4a9SWZQAT0r5agNUZKXT424EaRyM8fKQHXI

+ Response 200 (application/json)

          {
            "data": [
              {
                "id": 1,
                "stationSell": {
                    "link": "/api/v1/stationSells/5"
                },
                "station": {
                    "link": "/api/v1/user/company/4"
                }
              },
              {
                "id": 3,
                "stationSell": {
                    "link": "/api/v1/stationSells/8"
                },
                "station": {
                    "link": "/api/v1/user/company/4"
                }
              }
            ],
            "meta": {
            "pagination": {
              "total": 2,
              "count": 2,
              "per_page": 3,
              "current_page": 1,
              "total_pages": 1,
              "links": []
            }
          }

## Single Company Buy [/companyBuys/{companyBuy_id}]
### Show Company Buy [GET]

+ Parameters
    + companyBuy_id: 5 (number, required)

+ Request (application/json)
    
    + Headers
                
                Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xOTIuMTY4Ljk5LjEwMDo4MDgwXC9hcGlcL3YxXC9sb2dpbiIsImlhdCI6MTUzMjg4MzAxMCwiZXhwIjoxNTMyODg2NjEwLCJuYmYiOjE1MzI4ODMwMTAsImp0aSI6ImhOQ0wxTzBXa2s4VXJSOVIiLCJzdWIiOjQsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.3SUKcJbM4a9SWZQAT0r5agNUZKXT424EaRyM8fKQHXI

+ Response 200 (application/json)

          {
            "data": {
              "id": 3,
              "stationSell": {
                "link": "/api/v1/stationSells/8"
              },
              "station": {
                "link": "/api/v1/companies/4"
              }
            }
          }

+ Response 404 (application/json)

          {
            "error": {
              "message": "Could not buy of company",
              "status_code": 404,
            }
          }

### Delete CompanyBuy [DELETE]
+ Parameters
    + companyBuy_id: 5 (number, required)

+ Request (application/json)
    
    + Headers
                
                Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xOTIuMTY4Ljk5LjEwMDo4MDgwXC9hcGlcL3YxXC9sb2dpbiIsImlhdCI6MTUzMjg4MzAxMCwiZXhwIjoxNTMyODg2NjEwLCJuYmYiOjE1MzI4ODMwMTAsImp0aSI6ImhOQ0wxTzBXa2s4VXJSOVIiLCJzdWIiOjQsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.3SUKcJbM4a9SWZQAT0r5agNUZKXT424EaRyM8fKQHXI


+ Response 200 (application/json)

+ Response 404 (application/json)

        {
            "error": {
              "message": "Could not found buy of company",
              "status_code": 404
            }
          }
